### ISSUE TITLE
Update creating a Proxy Service doc

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#412]
## Description
Created this issue to track the changes for creating a Proxy Service feature for the MI VS Code extension.

Page to be updated: https://mi.docs.wso2.com/en/4.3.0/develop/creating-artifacts/creating-a-proxy-service/

Related Product issue: https://github.com/wso2/mi-vscode/issues/75

Currently there is no an option to generate proxy service using WSDL file. Therefore removed the [Creating a Proxy Service using a WSDL definition](https://mi.docs.wso2.com/en/4.2.0/develop/creating-artifacts/creating-a-proxy-service/#creating-a-proxy-service-using-a-wsdl-definition) section from the new doc space.

**Comment by rosensilva** [comment]
Need to implement WSDL to proxy generation feature in vs code

**Comment by chanikag** [comment]
Quoiting the comment from https://github.com/wso2/mi-vscode/issues/75
`When migrating the proxy service creation wizard from the Integration Studio to the MI extension it was decided to only support creation of a custom proxy and the other types to be supported via the diagram view after creating a proxy in order to allow them to be edited based on the user requirement. Therefore this issue cannot be addressed as we do not have a separate WSDL based proxy creation option now in the MI extension.`

As we are not adding this feature we will close this issue.
