### ISSUE TITLE
Write documentation for  Microsoft Azure Storage connector

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/docs-mi#481]
**Description:**

Write documentation for the Microsoft Azure Storage connector.
- Setting up the Microsoft Azure Storage connector.
- Sample scenario

**Comment by DinithiDiaz** [comment]
Closing the issue, since these pages have been added to the MI doc space.

- [Setting up the Microsoft Azure Storage Environment](https://mi.docs.wso2.com/en/latest/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-configuration/)
- [Microsoft Azure storage connector example 2.x](https://mi.docs.wso2.com/en/latest/reference/connectors/microsoft-azure-storage-connector/2.x/microsoft-azure-storage-connector-example/)
