### ISSUE TITLE
Few pages contains MI Dashboard instead of ICP

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#544]
## Description

We have missed updating `MI Dashboard` to `Integration Control Plane` in the following pages. We may need to update the screenshots as well

- https://mi.docs.wso2.com/en/4.3.0/install-and-setup/setup/user-stores/managing-users/#managing-users-and-roles-from-the-dashboard
- https://mi.docs.wso2.com/en/4.3.0/observe-and-manage/working-with-monitoring-dashboard/
- https://mi.docs.wso2.com/en/4.3.0/reference/config-catalog-mi-dashboard/
- https://mi.docs.wso2.com/en/4.3.0/observe-and-manage/working-with-management-api/
- https://mi.docs.wso2.com/en/4.3.0/observe-and-manage/observe-overview/#built-in-tools

**Comment by chanikag** [comment]
This is currently fixed. Identified few other issues 

- Page redirection issue for https://mi.docs.wso2.com/en/4.3.0/observe-and-manage/working-with-monitoring-dashboard/
- ICP was not listed in the https://mi.docs.wso2.com/en/4.3.0/reference/config-catalog-mi-dashboard/ 

Those are fixed with:
https://github.com/wso2/docs-mi/pull/869
