### ISSUE TITLE
Improvements for Quick start guide

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#791]
Suggested improvements for https://mi.docs.wso2.com/en/latest/get-started/quick-start-guide/#what-youll-build are as follows.

**ISSUE 1: Under step 1, it shows the diagram. But instructions are not given on how to open this diagram in the vscode.** 

<img width="957" alt="image" src="https://github.com/user-attachments/assets/3664f1e8-6c9f-44bd-a9fb-0f251257907b">

It seems the diagram is opening up by default only if we open `HealthcareIntegrationProject` folder directly in VS code. But if the user open the entire `mi-qsg-home` folder in vS code no way(at least i coudn't find) to open the **MI overview** panel. 

This is mentioned under step 2. But by the time the user reads the step2 , there is a high chance that user opened up the entire `mi-qsg-home`  folder in vscode and then no way to get the diagram. so need to either mention following in the first step or mention any alternative way of opening up the diagram.

<img width="965" alt="image" src="https://github.com/user-attachments/assets/b153f216-c49b-4e6d-8f0c-7835677340b4">

**ISSUE 2: It says `HealthcareIntegrationProject: This folder contains the integration artifacts for the healthcare service. This service consists of the following REST API:`  But actually the file is inside `/src/main/wso2mi/artifacts/apis` So it took a while to find the file. Better to mention about the file path.** 

<img width="997" alt="image" src="https://github.com/user-attachments/assets/e44f3816-b809-4382-8a5f-63cf945a582e">
<img width="321" alt="image" src="https://github.com/user-attachments/assets/ec2d218b-d349-4b47-bfc9-ba5f63f54990">

**ISSUE 3: Backend jar file name is missing.**
Suggestion: 

```Backend: This contains an executable `.jar` file named `DoctorInfo.jar' that contains mock back-end service implementations for the Pine Valley Hospital and Grand Oak Hospital``` 

<img width="976" alt="image" src="https://github.com/user-attachments/assets/07e302b9-16f8-4cc9-92ae-4fbdb9735864">

**ISSUE 4: In the following diagram both buttons are higlighted. Instead, highlight only the build button and possibly show the image with two options, as given in issue 5.**  The `export` button should be highlighted in step C. 

The same issue is there in page https://mi.docs.wso2.com/en/latest/get-started/development-kickstart/#option-2-use-a-local-micro-integrator-instance too

<img width="654" alt="image" src="https://github.com/user-attachments/assets/fba873fd-1c08-47ae-9633-0e7154dc8c15">

**ISSUE 5:  When building two options are popping up. It is not mentioned in the docs.** 

<img width="1319" alt="image" src="https://github.com/user-attachments/assets/04cabbd7-6687-45a3-8fbd-61acfaddcf58">

**ISSUE 6.  Repetitive start ICP steps.** 

In the [Step 3 - Observe deployed artifacts (Optional)](https://mi.docs.wso2.com/en/latest/get-started/quick-start-guide/#step-3-observe-deployed-artifacts-optional), under number 2, it says **Install and start** the Integration Control Plane (ICP) by following the steps below:. But we are not starting ICP here. Starting ICP is happenninng on number 3. So above sentense should be reworded. 

<img width="837" alt="image" src="https://github.com/user-attachments/assets/465b1523-9baa-4421-9c92-ed81f44972af">

**Comment by Bhashinee** [comment]
IMO, It is better to have a bare minimum of steps in the quickstart to run a simple application using the WSO2 MI like a "Hello World". Then we can move to more complex scenarios like building an integration scenario. In MI docs there is a section called `Develop your first integration` where we can go into more detail about different options and those monitoring-related things. In the current document the same scenario is repeated in both `Quick start` and `Develop your first integration`.

**Suggestions for `Quick Start Guide`**

Simplify the Initial Scenario: Instead of starting with a complex scenario under the "What you’ll build" section, we suggest starting with a "Build your first Hello World application" approach. This will help new users quickly become familiar with the MI VSCode extension and give a feeling that things can be easily run in MI before moving on to more advanced topics.

_**Step 1: Set Up the Workspace**_

Instead of asking the users to download the samples and open them in Visual Studio Code, simply select the "Hello World Service" provided under the `Explore Samples` section in the VS Code extension. Choose a folder where you want to create the "HelloWorld" service.
<img width="1392" alt="Screenshot 2024-08-27 at 13 36 05" src="https://github.com/user-attachments/assets/df6ba29d-a2e4-4a7a-9cd4-8c7b668c7c2e">

Expand the `APIs/HelloWorld` folder and click on the API listed there. You will see the REST API diagram.

<img width="1085" alt="Screenshot 2024-08-27 at 13 39 39" src="https://github.com/user-attachments/assets/bb134e66-cf58-4b83-9b00-7ccc3b42d338">

Briefly explain what it does (Once the service is invoked, it responds with "Hello World". You have a `PayloadFactory` with the value `{"Hello":"World"}` and `Respond` is used to send the message set in the `PayloadFactory` to the client).

_**Step 2: Run the Integration Artifacts**_

Instead of offering two options (`using Visual Studio Code` and `using a local Micro Integrator instance`), only provide the first option - running it using Visual Studio Code.

The alternative option of building and exporting as a CAPP can be detailed in the `Develop your first integration` section of the MI documentation.

_**Step 3: Observe Deployed Artifacts (Optional)**_

In my opinion, this step may not be necessary in the quickstart guide. It can be omitted to keep the guide simple and focused on getting a simple Hello World to run.

_**Step 4: Test the Integration Service**_

Use a simple curl command to invoke the Hello World service and verify its functionality.

**Comment by anupama-pathirage** [comment]
+1 for all the suggestions. 

@isudana thoughts?

**Comment by pcnfernando** [comment]
+1 for all. 

Shall we use gifs/images to show the development phases of the helloWorld service along with the description? 
Plus, we could have users jump into the source view and personalize it by adding their name.

May be include references to access extra help. (faq,discord..)

**Comment by rosensilva** [comment]
+1 for the suggestions.
Is it better to improve the MI onboarding user experience as discussed in https://github.com/wso2-enterprise/integration-product-management/issues/169 and then update the doc accordingly?

**Comment by pcnfernando** [comment]
@rosensilva We thought of first polishing the existing version since it could be done quickly. 

Secondly, to revisit the onboarding process and sync the guides accordingly.

**Comment by anupama-pathirage** [comment]
@Bhashinee what is the effort estimate for this doc update? I hope it is not taking much time.

**Comment by Bhashinee** [comment]
> @Bhashinee what is the effort estimate for this doc update? I hope it is not taking much time.

Yes, unlike the other changes that would require technical changes, these are just documentation updates. We can implement the suggested changes within a day.

**Comment by chanikag** [comment]
PR: https://github.com/wso2/docs-mi/pull/977
